vich_uploader:
    db_driver: orm

    mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

        image:
            uri_prefix:         /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            directory_namer:
                service: vich_uploader.directory_namer_subdir
                options: {chars_per_dir: 3, dirs: 3}